//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pract_ima
{
    using System;
    using System.Collections.Generic;
    
    public partial class Устройства
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Устройства()
        {
            this.Журнал_датчиков = new HashSet<Журнал_датчиков>();
        }
    
        public int ID_устройства { get; set; }
        public int ID_комнаты { get; set; }
        public string Тип { get; set; }
        public string Название { get; set; }
        public string Статус { get; set; }
        public string Текущее_значение { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Журнал_датчиков> Журнал_датчиков { get; set; }
        public virtual Комнаты Комнаты { get; set; }
    }
}
